"""SPEC-011: export the admin-panel OpenAPI subset (CI-compatible static artifact).

Generates ``docs/openapi-admin.json`` from the FastAPI app schema, keeping only
the ``/api/v1/admin`` paths and the component schemas they reference
(transitively). Run from anywhere:

    python backend/scripts/export_openapi_admin.py

The committed JSON is a static snapshot; CI can regenerate it and diff against
git to catch undocumented API drift.
"""
from __future__ import annotations

import json
import os
import sys

SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))          # backend/scripts
BACKEND_DIR = os.path.dirname(SCRIPTS_DIR)                        # backend
REPO_ROOT = os.path.dirname(BACKEND_DIR)                          # repo root
OUT_PATH = os.path.join(REPO_ROOT, "docs", "openapi-admin.json")
PREFIX = "/api/v1/admin"


def main() -> None:
    sys.path.insert(0, BACKEND_DIR)
    # OpenAPI generation must not require a live database.
    os.environ.setdefault("DATABASE_URL", "sqlite:///./openapi_snapshot.db")

    from app.main import app  # noqa: WPS433 (script)

    schema = app.openapi()
    schema["info"]["title"] = "Fitness Tracker — Admin Panel API (SPEC-011)"
    schema["info"]["description"] = (
        "OpenAPI subset of the Fitness Tracker API for the admin panel "
        "(SPEC-011). Generated by backend/scripts/export_openapi_admin.py — "
        "do not edit by hand."
    )

    admin_paths = {p: spec for p, spec in schema.get("paths", {}).items() if p.startswith(PREFIX)}
    schemas = schema.get("components", {}).get("schemas", {})
    wanted: set[str] = set()

    def collect_ref(ref: str) -> None:
        name = ref.split("/")[-1]
        if name in schemas and name not in wanted:
            wanted.add(name)
            walk(schemas[name])

    def walk(node) -> None:
        if isinstance(node, dict):
            for key, value in node.items():
                if key == "$ref" and isinstance(value, str):
                    collect_ref(value)
                else:
                    walk(value)
        elif isinstance(node, list):
            for item in node:
                walk(item)

    for spec in admin_paths.values():
        walk(spec)

    schema["paths"] = admin_paths
    components = schema.get("components")
    if components is not None:
        kept = {name: schemas[name] for name in sorted(wanted) if name in schemas}
        if "schemas" in components:
            components["schemas"] = kept

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        json.dump(schema, f, ensure_ascii=False, indent=2, sort_keys=True)
        f.write("\n")
    print(f"wrote {os.path.relpath(OUT_PATH)} ({len(admin_paths)} admin paths, {len(wanted)} schemas)")


if __name__ == "__main__":
    main()
